
```{r}
library(data.table)
library(readxl)
library(ggplot2)
library(maptools)
library(foreign)
library(plyr)
library(haven)
```

```{r}
knitr::opts_knit$set(root.dir = normalizePath("/Volumes/GoogleDrive/My Drive/SRTR"))
getwd()
```

```{r}
# Time to read 1 yr's file = 36 sec.
Sys.time()
df18 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20180101_20181231.csv")
df17 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20170101_20171231.csv")
df16 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20160101_20161231.csv")
df15 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20150101_20151231.csv")
df14 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20140101_20141231.csv")
df13 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20130101_20131231.csv")
df12 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20120101_20121231.csv")
df11 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20110101_20111231.csv")
df10 = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/LiverMatchRun/ptr_li_20100101_20101231.csv")

Sys.time()
```

```{r}
df10$date = as.Date(df10$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df11$date = as.Date(df11$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df12$date = as.Date(df12$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df13$date = as.Date(df13$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df14$date = as.Date(df14$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df15$date = as.Date(df15$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df16$date = as.Date(df16$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df17$date = as.Date(df17$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
df18$date = as.Date(df18$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
```


```{r}
# Policy column:
df10$policy = "pre"
df11$policy = "pre"
df12$policy = "pre"
df13$policy = sapply(c(1:nrow(df13)), function(i) {if (df13$date[i] > "2013-06-17") {return ("post")} else {return ("pre")}}) 
df14$policy = "post"
df15$policy = "post"
df16$policy = "post"
df17$policy = "post"
df18$policy = "post"
```

```{r}
# To check if all the 1 yr files have also records from previous year and next year:  YES, they have!
min(df10$date); max(df10$date)
min(df11$date); max(df11$date)
min(df12$date); max(df12$date)
min(df13$date); max(df13$date)
min(df14$date); max(df14$date)
min(df15$date); max(df15$date)
min(df16$date); max(df16$date)
min(df17$date); max(df17$date)
min(df18$date); max(df18$date)
```
```{r}
df10$yr_mon = substr(as.character(df10$MATCH_SUBMIT_DT), 1, 7)
df11$yr_mon = substr(as.character(df11$MATCH_SUBMIT_DT), 1, 7)
df12$yr_mon = substr(as.character(df12$MATCH_SUBMIT_DT), 1, 7)
df13$yr_mon = substr(as.character(df13$MATCH_SUBMIT_DT), 1, 7)
df14$yr_mon = substr(as.character(df14$MATCH_SUBMIT_DT), 1, 7)
df15$yr_mon = substr(as.character(df15$MATCH_SUBMIT_DT), 1, 7)
df16$yr_mon = substr(as.character(df16$MATCH_SUBMIT_DT), 1, 7)
df17$yr_mon = substr(as.character(df17$MATCH_SUBMIT_DT), 1, 7)
df18$yr_mon = substr(as.character(df18$MATCH_SUBMIT_DT), 1, 7)
unique(df18$yr_mon)

df_all = rbind(df10[!(df10$yr_mon %in% c("2009-12", "2011-01")), ], df11[!(df11$yr_mon %in% c("2010-12", "2012-01")), ])
df_all = rbind(df_all, df12[!(df12$yr_mon %in% c("2011-12", "2013-01")), ])
df_all = rbind(df_all, df13[!(df13$yr_mon %in% c("2012-12", "2014-01")), ])
df_all = rbind(df_all, df14[!(df14$yr_mon %in% c("2013-12", "2015-01")), ])
df_all = rbind(df_all, df15[!(df15$yr_mon %in% c("2014-12", "2016-01")), ])
df_all = rbind(df_all, df16[!(df16$yr_mon %in% c("2015-12", "2017-01")), ])
df_all = rbind(df_all, df17[!(df17$yr_mon %in% c("2016-12", "2018-01")), ])
df_all = rbind(df_all, df18[!(df18$yr_mon %in% c("2017-12", "2019-01")), ])

uniqueN(df_all$MATCH_ID)
unique(df_all$yr_mon)
unique(df14$yr_mon)
```



```{r}
#df_all = do.call("rbind", list(df18, df17, df16, df15, df14, df13, df12, df11, df10))
#df_all$date = as.Date(df_all$MATCH_SUBMIT_DT, format= "%Y-%m-%d")
```

```{r}
temp17 = df17[df17$MATCH_ID == "1079231", ]
temp18 = df18[df18$MATCH_ID == "1079231", ]
temp1 = df_all[df_all$MATCH_ID == "1079231", ]
```

```{r}
print (uniqueN(df18$MATCH_ID) + uniqueN(df17$MATCH_ID) + uniqueN(df16$MATCH_ID) + uniqueN(df15$MATCH_ID) + uniqueN(df14$MATCH_ID) + uniqueN(df13$MATCH_ID) + uniqueN(df12$MATCH_ID) + uniqueN(df11$MATCH_ID) + uniqueN(df10$MATCH_ID))

print (uniqueN(df_all$MATCH_ID))
```

```{r}
print (uniqueN(df18$DONOR_ID) + uniqueN(df17$DONOR_ID) + uniqueN(df16$DONOR_ID) + uniqueN(df15$DONOR_ID) + uniqueN(df14$DONOR_ID) + uniqueN(df13$DONOR_ID) + uniqueN(df12$DONOR_ID) + uniqueN(df11$DONOR_ID) + uniqueN(df10$DONOR_ID))

print (uniqueN(df_all$DONOR_ID))
```

```{r}
table(df_all$MATCH_ORG)
table()
```

```{r}
# Remove prefix 'b' from the column enteries:
df_all$MATCH_ORG = "LI"    # Since the enteries were either "LI" or "b'LI"
temp = df_all[1:10, ]

df_all$MATCH_OPO_CTR_CD = as.character(df_all$MATCH_OPO_CTR_CD)
df_all$MATCH_OPO_CTR_CD = gsub("b'", "", df_all$MATCH_OPO_CTR_CD)
df_all$MATCH_OPO_CTR_CD = gsub("'", "", df_all$MATCH_OPO_CTR_CD)

df_all$MATCH_OPO_CTR_TY = as.character(df_all$MATCH_OPO_CTR_TY)
df_all$MATCH_OPO_CTR_TY = gsub("b'", "", df_all$MATCH_OPO_CTR_TY)
df_all$MATCH_OPO_CTR_TY = gsub("'", "", df_all$MATCH_OPO_CTR_TY)

df_all$PTR_CLASS_ALLOC_CAT = as.character(df_all$PTR_CLASS_ALLOC_CAT)
df_all$PTR_CLASS_ALLOC_CAT = gsub("b'", "", df_all$PTR_CLASS_ALLOC_CAT)
df_all$PTR_CLASS_ALLOC_CAT = gsub("'", "", df_all$PTR_CLASS_ALLOC_CAT)

df_all$PTR_CLASS_ALLOC_CAT = as.character(df_all$PTR_CLASS_ALLOC_CAT)
df_all$PTR_CLASS_ALLOC_CAT = gsub("b'", "", df_all$PTR_CLASS_ALLOC_CAT)
df_all$PTR_CLASS_ALLOC_CAT = gsub("'", "", df_all$PTR_CLASS_ALLOC_CAT)

df_all$PTR_OFFER_ACPT = as.character(df_all$PTR_OFFER_ACPT)
df_all$PTR_OFFER_ACPT = gsub("b'", "", df_all$PTR_OFFER_ACPT)
df_all$PTR_OFFER_ACPT = gsub("'", "", df_all$PTR_OFFER_ACPT)

df_all$PTR_ORG_PLACED = as.character(df_all$PTR_ORG_PLACED)
df_all$PTR_ORG_PLACED = gsub("b'", "", df_all$PTR_ORG_PLACED)
df_all$PTR_ORG_PLACED = gsub("'", "", df_all$PTR_ORG_PLACED)
```

```{r}
# Save the merged file.
write.csv(df_all, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_10_18.csv", row.names = F)
df_all_src = df_all
```

```{r}
df_all = df_all_src
# Linking with INSTITUTION data:
inst = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/institution.csv")
temp = inst[, c("CTR_CD", "REGION")]  # NOTE: There are 2 cities for "CASU", "FLFH", "MOSL", "NCBG"!
# Therefore, not merging the CITIES!
temp$CTR_CD = as.character(temp$CTR_CD)
temp$CTR_CD = gsub("b'", "", temp$CTR_CD)
temp$CTR_CD = gsub("'", "", temp$CTR_CD)
# temp$PRIMARY_CITY = as.character(temp$PRIMARY_CITY)
# temp$PRIMARY_CITY = gsub("b'", "", temp$PRIMARY_CITY)
# temp$PRIMARY_CITY = gsub("'", "", temp$PRIMARY_CITY)
colnames(temp) = c("CTR_CD", "MATCH_OPO_REGION")
temp = unique(temp)
# temp2 = data.table(temp)[, list(cnt_Region = uniqueN(MATCH_OPO_PRIMARY_CITY)), by = CTR_CD]

df_all = merge(df_all, temp, by.x = "MATCH_OPO_CTR_CD", by.y = "CTR_CD", all.x = T)

```

```{r}
# Adding 'PTR_STAT_CD'
temp = read_excel("/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_sample.xlsx", sheet = "PTR_STAT_CD")
temp = as.data.frame(temp)
temp[, 1] = as.character(temp[, 1])
samp_match = df_all[1:200,]
df_all = merge(df_all, temp, by.x = "PTR_STAT_CD", by.y = "Candidate's current Medical Urgency", all.x = T)

df_all$yr = substr(df_all$MATCH_SUBMIT_DT, 1, 4)
#write.csv(df_all, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_10_18.csv", row.names = F)
table(df_all$yr)
```
```{r}
# # of MATCH_IDs per DONOR_ID:
temp = data.table(df_all)[, list(MATCH_ID_cnt = uniqueN(MATCH_ID)), by = DONOR_ID]
max(temp$MATCH_ID_cnt)
table(temp$MATCH_ID_cnt)/nrow(temp)

df_all = merge(df_all, temp, by = "DONOR_ID", all.x = T)

# Checking if one MATCH_ID has multiple "Y":
temp = data.table(df_all)[, list(MATCH_Y_cnt = sum(PTR_OFFER_ACPT == "Y")), by = MATCH_ID]
table(temp$MATCH_Y_cnt)

lst = c(temp[temp$MATCH_Y_cnt > 1, "MATCH_ID"])$MATCH_ID
table(df_all[df_all$MATCH_ID %in% lst, "PTR_ORG_PLACED"])
df_all[(df_all$MATCH_ID %in% lst) & df_all$PTR_ORG_PLACED == "LI-W", "MATCH_ID"]
df_all[(df_all$MATCH_ID == 1131808) & df_all$PTR_ORG_PLACED == "LI-W", "PTR_ORG_PLACED"] = "LI-S"
```

```{r}
# Adding the result of organ placement type (LI-S or LI-W) and # Y decisions for each of MATCH_ID:
f1 = function(PTR_OFFER_ACPT) {
  lst = unique(PTR_OFFER_ACPT)
  lst = lst[lst != ""]
  return (lst)
}

temp2 = data.table(df_all)[, list(MATCH_cnt_Y = sum(PTR_OFFER_ACPT == "Y"), MATCH_PTR_ORG_PLACED_type = f1(PTR_ORG_PLACED)), by = MATCH_ID]
temp2[is.na(temp2$MATCH_cnt_Y), "MATCH_cnt_Y"] = 0
temp2[is.na(temp2$MATCH_PTR_ORG_PLACED_type), "MATCH_PTR_ORG_PLACED_type"] = "not_placed"
table(temp2$MATCH_cnt_Y)
table(temp2$MATCH_PTR_ORG_PLACED_type)

df_all = merge(df_all, temp2, by = "MATCH_ID", all.x = T)
uniqueN(temp2$MATCH_ID)

# Adding the result of organ placement type (LI-S or LI-W) and # Y decisions for each of DONOR_ID:
f1 = function(PTR_OFFER_ACPT) {
  lst = unique(PTR_OFFER_ACPT)
  lst = lst[lst != ""]
  if (length(lst) == 0) {
    return ("not_placed")
  } else if (length(lst) == 2) {
    return ("LI-S_LI-W")
  } else { return (lst)}
}

temp2 = data.table(df_all)[, list(DONOR_cnt_Y = sum(PTR_OFFER_ACPT == "Y"), DONOR_PTR_ORG_PLACED_type = f1(PTR_ORG_PLACED)), by = DONOR_ID]
nrow(temp2); uniqueN(temp2$DONOR_ID)
table(temp2$DONOR_cnt_Y)
table(temp2$DONOR_PTR_ORG_PLACED_type)

df_all = merge(df_all, temp2, by = "DONOR_ID", all.x = T)
```


```{r}
# Save the merged file.
write.csv(df_all, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_10_18.csv", row.names = F)
```

# Donor Data:
```{r}
# No. of liver arrivals per month:
df_don = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/donor_deceased.csv")
#names(df_don)
```


```{r}
df_don$date <- as.Date(df_don$DON_RECOV_DT, format= "%Y-%m-%d")
df_don$yr_mon = substr(as.character(df_don$DON_RECOV_DT), 1, 7)
df_don$yr = substr(df_don$date, 1, 4)
df_don1 = df_don[, c("DON_RECOV_DT", "date", "yr_mon", "PERS_ID", "DONOR_ID", "DON_TX", "DON_OPO_CTR_ID", "DON_ABO", "DON_AGE", "DON_AGE_IN_MONTHS", "DON_GENDER", "DON_HGT_CM", "DON_WGT_KG", "DON_RACE", "DON_RACE_SRTR", "DON_TY", "DON_CAD_DON_COD", "DON_COD_DON_STROKE", "DON_DEATH_MECH", "DON_ALLOC_REMAIN_LI_SEG", "DON_HBC_STAT", "DON_HCV_STAT", "DON_ANTI_HCV", "DON_ANTI_HIV", "DON_ANTI_HYPERTEN", "DON_HEAVY_ALCOHOL", "DON_HIST_ALCOHOL", "DON_CONT_ALCOHOL", "DON_HIST_CIGARETTE_GT20_PKYR", "DON_CONT_CIGARETTE", "DON_HIST_COCAINE", "DON_CONT_COCAINE", "DON_HIST_IV_DRUG", "DON_CONT_IV_DRUG", "DON_HIST_CANCER", "DON_HIST_DIAB", "DON_HIST_INSULIN_DEPND", "DON_HTN", "DON_HIST_HYPERTEN", "DON_ALLOC_ECD_HYPERTEN", "DON_DCD_PROGRESS_TO_BRAIN_DEATH", "DON_DCD_SUPPORT_WITHDRAW_DT", "DON_DCD_SUPPORT_WITHDRAW_TM", "DON_HOME_STATE")]

```

```{r}
df_don1[1:10, ]
unique(df_don1$DON_OPO_CTR_ID)
```

```{r}
df_don11 = as.data.frame(subset(df_don1, date > "2009-12-31"))
df_don11[1:10, ]
min(df_don11$date)
```


```{r}
# Linking with INSTITUTION data:
inst = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/institution.csv")

temp = inst[, c("CTR_ID", "CTR_CD", "CTR_TY", "REGION", "PRIMARY_CITY")] 
colnames(temp) = c("CTR_ID", "DON_OPO_CTR_CD", "DON_OPO_CTR_TY", "DON_OPO_REGION", "DON_OPO_PRIMARY_CITY")

df_don12 = merge(df_don11, temp, by.x = "DON_OPO_CTR_ID", by.y = "CTR_ID", all.x = T)
df_don12[1:5,]
```

```{r}
# Linking with DISPOSITION data:
DISP = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/donor_disposition.csv")

DISP$date <- as.Date(DISP$DON_RECOV_DT, format= "%Y-%m-%d")
DISP1 = subset(DISP, date > "2009-12-31")
DISP1[1:5,]
min(DISP1$date)

DISP1 = DISP1[, c("DONOR_ID", "DON_ORG", "DON_TX_CTR_ID", "MATCH_ID", "PX_ID", "DON_DISCARD_CD", "DON_DISPOSITION", "DON_REASON_CD")]
summary(DISP1$DON_ORG)
DISP1$DON_ORG = as.character(DISP1$DON_ORG)
unique(DISP1$DON_ORG)
DISP1_LI = DISP1[DISP1$DON_ORG == "b'LI'", ]
```

```{r}
df_don13 = merge(df_don12, DISP1_LI, by = "DONOR_ID", all.x = T)
df_don13$policy = sapply(c(1:nrow(df_don13)), function(i) {if (df_don13$date[i] > "2013-06-17") {return ("post")} else {return ("pre")}}) 
table(df_don13$DON_ORG); table(df_don13$policy)
```

```{r}
for (col in c("DON_ABO", "DON_GENDER", "DON_HOME_STATE", "DON_OPO_PRIMARY_CITY", "DON_ORG", "DON_RACE_SRTR", "DON_TY", "DON_ALLOC_REMAIN_LI_SEG", "DON_ANTI_HCV", "DON_ANTI_HIV", "DON_ANTI_HYPERTEN", "DON_HEAVY_ALCOHOL", "DON_HIST_CIGARETTE_GT20_PKYR", "DON_CONT_CIGARETTE", "DON_CONT_COCAINE", "DON_HIST_COCAINE", "DON_DCD_PROGRESS_TO_BRAIN_DEATH")) {
  df_don13[, col] = as.character(df_don13[, col])
  df_don13[, col] = gsub("b'", "", df_don13[, col])
  df_don13[, col] = gsub("'", "", df_don13[, col])
}
```

```{r}
# Adding column descriptions:
temp = read_excel("/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_sample.xlsx", sheet = "DON_data")
temp = as.data.frame(temp)
names(temp)
temp[, ] = lapply(temp[, ], as.character)

df_don13 = merge(df_don13, temp[1:6, c("DON_CAD_DON_COD", "DON_CAD_DON_COD_desp")], by = "DON_CAD_DON_COD", all.x = T)
df_don13 = merge(df_don13, temp[1:15, c("DON_DEATH_MECH", "DON_DEATH_MECH_desp")], by = "DON_DEATH_MECH", all.x = T)
df_don13 = merge(df_don13, temp[1:7, c("DON_HBC_STAT", "DON_HBC_STAT_desp")], by = "DON_HBC_STAT", all.x = T)
df_don13 = merge(df_don13, temp[1:7, c("DON_HCV_STAT", "DON_HCV_STAT_desp")], by = "DON_HCV_STAT", all.x = T)
df_don13 = merge(df_don13, temp[1:34, c("DON_HIST_CANCER", "DON_HIST_CANCER_desp")], by = "DON_HIST_CANCER", all.x = T)
df_don13 = merge(df_don13, temp[1:6, c("DON_HIST_DIAB", "DON_HIST_DIAB_desp")], by = "DON_HIST_DIAB", all.x = T)
df_don13 = merge(df_don13, temp[1:21, c("DON_DISCARD_CD", "DON_DISCARD_CD_desp")], by = "DON_DISCARD_CD", all.x = T)

names(df_don13)
df_don13 = df_don13[, c(8:23, 7, 57, 6, 58, 24:25, 5, 59, 4, 60, 26:41, 3, 61, 2, 62, 42:56, 1, 63)]

df_don13$DON_CAD_DON_COD_desp = as.character(df_don13$DON_CAD_DON_COD_desp)
df_don13$DON_CAD_DON_COD_desp = gsub("^\\s+|\\s+$", "", df_don13$DON_CAD_DON_COD_desp)    # Trim the whitespaces
unique(df_don13$DON_CAD_DON_COD_desp)
```

```{r}
write.csv(df_don13, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/donor.csv", row.names = F)
temp = df_don13[1:8, ]
```

# Transplantation data:
```{r}
tx = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/tx_li.csv")
tx$date <- as.Date(tx$REC_TX_DT, format= "%Y-%m-%d")
tx1 = subset(tx, date > "2009-12-31")
tx1[1:5,]
min(tx1$date)

# Linking with INSTITUTION data:
inst = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/institution.csv")

temp = inst[, c("CTR_ID", "CTR_CD", "CTR_TY", "REGION", "PRIMARY_CITY")]
colnames(temp) = c("CTR_ID", "REC_CTR_CD", "REC_CTR_TY", "REC_REGION", "REC_PRIMARY_CITY")
tx1 = merge(tx1, temp, by.x = "REC_CTR_ID", by.y = "CTR_ID", all.x = T)

colnames(temp) = c("CTR_ID", "REC_OPO_CD", "REC_OPO_TY", "REC_OPO_REGION", "REC_OPO_PRIMARY_CITY")
tx1 = merge(tx1, temp, by.x = "REC_OPO_ID", by.y = "CTR_ID", all.x = T)

colnames(temp) = c("CTR_ID", "DON_OPO_CD", "DON_OPO_TY", "DON_OPO_REGION", "DON_OPO_PRIMARY_CITY")
tx1 = merge(tx1, temp, by.x = "DON_OPO_CTR_ID", by.y = "CTR_ID", all.x = T)

#names(tx1$REC_WARM_ISCH_TM)

tx1 = tx1[, c("REC_TX_DT", "date", "PX_ID", "PERS_ID", "CAN_ABO", "REC_COLD_ISCH_TM", "REC_WARM_ISCH_TM", "CAN_LISTING_DT", "CAN_AGE_AT_LISTING", "CAN_AGE_IN_MONTHS_AT_LISTING", "REC_AGE_AT_TX", "REC_AGE_IN_MONTHS_AT_TX", "REC_CTR_ID", "REC_CTR_CD", "REC_CTR_TY", "REC_REGION", "REC_PRIMARY_CITY", "REC_OPO_ID", "REC_OPO_CD", "REC_OPO_TY", "REC_OPO_REGION", "REC_OPO_PRIMARY_CITY", "REC_PERM_STATE", "REC_PREV_LI", "CAN_GENDER", "CAN_INIT_SRTR_LAB_MELD", "CAN_INIT_SRTR_LAB_MELD_TY", "CAN_INIT_STAT", "CAN_LAST_SRTR_LAB_MELD", "CAN_LAST_SRTR_LAB_MELD_TY", "CAN_LAST_STAT", "CAN_PREV_LI", "CAN_REM_CD", "CAN_SOURCE", "CAN_WGT_KG", "DONOR_ID", "DON_OPO_CTR_ID", "DON_OPO_CD", "DON_OPO_TY", "DON_OPO_REGION", "DON_OPO_PRIMARY_CITY", "DON_ABO", "DON_AGE", "DON_AGE_IN_MONTHS", "DON_CAD_DON_COD", "DON_DEATH_MECH", "DON_GENDER", "REC_A_MM_EQUIV_CUR", "REC_A_MM_EQUIV_TX", "REC_B_MM_EQUIV_CUR", "REC_B_MM_EQUIV_TX", "REC_DR_MM_EQUIV_CUR", "REC_DR_MM_EQUIV_TX", "REC_MM_EQUIV_CUR", "REC_MM_EQUIV_TX")]
```

```{r}
tx1$CAN_ABO = as.character(tx1$CAN_ABO)
tx1$CAN_ABO = gsub("b'", "", tx1$CAN_ABO)
tx1$CAN_ABO = gsub("'", "", tx1$CAN_ABO)

tx1$REC_PRIMARY_CITY = as.character(tx1$REC_PRIMARY_CITY)
tx1$REC_PRIMARY_CITY = gsub("b'", "", tx1$REC_PRIMARY_CITY)
tx1$REC_PRIMARY_CITY = gsub("'", "", tx1$REC_PRIMARY_CITY)

tx1$REC_OPO_PRIMARY_CITY = as.character(tx1$REC_OPO_PRIMARY_CITY)
tx1$REC_OPO_PRIMARY_CITY = gsub("b'", "", tx1$REC_OPO_PRIMARY_CITY)
tx1$REC_OPO_PRIMARY_CITY = gsub("'", "", tx1$REC_OPO_PRIMARY_CITY)

tx1$REC_PERM_STATE = as.character(tx1$REC_PERM_STATE)
tx1$REC_PERM_STATE = gsub("b'", "", tx1$REC_PERM_STATE)
tx1$REC_PERM_STATE = gsub("'", "", tx1$REC_PERM_STATE)

tx1$CAN_GENDER = as.character(tx1$CAN_GENDER)
tx1$CAN_GENDER = gsub("b'", "", tx1$CAN_GENDER)
tx1$CAN_GENDER = gsub("'", "", tx1$CAN_GENDER)

tx1$CAN_INIT_SRTR_LAB_MELD_TY = as.character(tx1$CAN_INIT_SRTR_LAB_MELD_TY)
tx1$CAN_INIT_SRTR_LAB_MELD_TY = gsub("b'", "", tx1$CAN_INIT_SRTR_LAB_MELD_TY)
tx1$CAN_INIT_SRTR_LAB_MELD_TY = gsub("'", "", tx1$CAN_INIT_SRTR_LAB_MELD_TY)

tx1$CAN_LAST_SRTR_LAB_MELD_TY = as.character(tx1$CAN_LAST_SRTR_LAB_MELD_TY)
tx1$CAN_LAST_SRTR_LAB_MELD_TY = gsub("b'", "", tx1$CAN_LAST_SRTR_LAB_MELD_TY)
tx1$CAN_LAST_SRTR_LAB_MELD_TY = gsub("'", "", tx1$CAN_LAST_SRTR_LAB_MELD_TY)

tx1$CAN_SOURCE = as.character(tx1$CAN_SOURCE)
tx1$CAN_SOURCE = gsub("b'", "", tx1$CAN_SOURCE)
tx1$CAN_SOURCE = gsub("'", "", tx1$CAN_SOURCE)

tx1$DON_OPO_PRIMARY_CITY = as.character(tx1$DON_OPO_PRIMARY_CITY)
tx1$DON_OPO_PRIMARY_CITY = gsub("b'", "", tx1$DON_OPO_PRIMARY_CITY)
tx1$DON_OPO_PRIMARY_CITY = gsub("'", "", tx1$DON_OPO_PRIMARY_CITY)

tx1$DON_ABO = as.character(tx1$DON_ABO)
tx1$DON_ABO = gsub("b'", "", tx1$DON_ABO)
tx1$DON_ABO = gsub("'", "", tx1$DON_ABO)

tx1$DON_GENDER = as.character(tx1$DON_GENDER)
tx1$DON_GENDER = gsub("b'", "", tx1$DON_GENDER)
tx1$DON_GENDER = gsub("'", "", tx1$DON_GENDER)
```

```{r}
summary(tx1$REC_AGE_IN_MONTHS_AT_TX - tx1$CAN_AGE_IN_MONTHS_AT_LISTING)
hist(tx1$REC_COLD_ISCH_TM, breaks=50); summary(tx1$REC_COLD_ISCH_TM)

write.csv(tx1, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/tx.csv", row.names = F)
```

# Waiting Patients Info:
```{r}
wp = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/cand_liin.csv")
names(wp)

wp$actv_date <- as.Date(wp$CAN_ACTIVATE_DT, format= "%Y-%m-%d")
wp$list_date <- as.Date(wp$CAN_LISTING_DT, format= "%Y-%m-%d")

min(wp[!is.na(wp$list_date), "list_date"] - wp[!is.na(wp$actv_date), "actv_date"])

wp1 = subset(wp, actv_date > "2002-12-31")
wp1[1:5,]
summary(wp1$PERS_NEXTTX); summary(wp1$DONOR_ID)
summary(wp1$WL_ORG)

wp1$WL_ORG = as.character(wp1$WL_ORG)
unique(wp1$WL_ORG)
wp1_LI = wp1[wp1$WL_ORG == "b'LI'", ]
wp1$WL_ORG = "LI"

summary(wp1_LI$CAN_FOLLOWS_OPO_ALLOC)

summary(wp1_LI$CAN_SOURCE)

temp = inst[, c("CTR_ID", "CTR_CD", "CTR_TY", "REGION", "PRIMARY_CITY")]
colnames(temp) = c("CTR_ID", "CAN_CTR_CD", "CAN_CTR_TY", "CAN_REGION", "CAN_PRIMARY_CITY")
wp1_LI = merge(wp1_LI, temp, by.x = "CAN_LISTING_CTR_ID", by.y = "CTR_ID", all.x = T)

colnames(temp) = c("CTR_ID", "CAN_OPO_CD", "CAN_OPO_TY", "CAN_OPO_REGION", "CAN_OPO_PRIMARY_CITY")
wp1_LI = merge(wp1_LI, temp, by.x = "CAN_LISTING_OPO_ID", by.y = "CTR_ID", all.x = T)

wp1_LI = wp1_LI[, c("PX_ID", "PERS_ID", "list_date", "CAN_LISTING_DT", "actv_date", "CAN_ACTIVATE_DT", "CAN_SOURCE", "CAN_ABO", "CAN_ACPT_A2_DON", "CAN_ACPT_ABO_INCOMP", "CAN_ACPT_EXTRACORP_LI", "CAN_ACPT_HBC_POS", "CAN_ACPT_HCV_POS", "CAN_AGE_AT_LISTING", "CAN_AGE_IN_MONTHS_AT_LISTING", "CAN_DEATH_DT", "CAN_GENDER", "CAN_HGT_CM", "CAN_MOST_RECENT_HGT_CM", "CAN_MOST_RECENT_WGT_KG", "CAN_INIT_SRTR_LAB_MELD", "CAN_INIT_SRTR_LAB_MELD_TY", "CAN_INIT_STAT", "CAN_LAST_SRTR_LAB_MELD", "CAN_LAST_SRTR_LAB_MELD_TY", "CAN_LAST_STAT", "CAN_LISTING_CTR_ID", "CAN_CTR_CD", "CAN_CTR_TY", "CAN_REGION", "CAN_PRIMARY_CITY", "CAN_LISTING_OPO_ID", "CAN_OPO_CD", "CAN_OPO_TY", "CAN_OPO_REGION", "CAN_OPO_PRIMARY_CITY", "CAN_LIVING_DON_TX", "CAN_MAX_AGE", "CAN_MAX_MILE", "CAN_MAX_WGT", "CAN_PREV_LI", "CAN_REM_CD", "CAN_REM_COD", "CAN_REM_DT", "DONOR_ID", "DON_TY", "PERS_NEXTTX", "PERS_NEXTTX_TRR_ID", "REC_TX_DT", "REC_TX_PROCEDURE_TY")]
```

```{r}
lst = c(colnames(wp1_LI)[7:13], colnames(wp1_LI)[17], colnames(wp1_LI)[22], colnames(wp1_LI)[25], colnames(wp1_LI)[46])
for (col in lst) {
  wp1_LI[, col] = as.character(wp1_LI[, col])
  wp1_LI[, col] = gsub("b'", "", wp1_LI[, col])
  wp1_LI[, col] = gsub("'", "", wp1_LI[, col])
}
```

```{r}
# Adding 'PTR_STAT_CD'
temp = read_excel("/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_sample.xlsx", sheet = "PTR_STAT_CD")
temp = as.data.frame(temp)
temp[, 1] = as.character(temp[, 1])
names(temp)[2] = "CAN_INIT_STAT_desp"
wp1_LI = merge(wp1_LI, temp, by.x = "CAN_INIT_STAT", by.y = "Candidate's current Medical Urgency", all.x = T)
names(temp)[2] = "CAN_INIT_SRTR_LAB_MELD_desp"
wp1_LI = merge(wp1_LI, temp, by.x = "CAN_INIT_SRTR_LAB_MELD", by.y = "Candidate's current Medical Urgency", all.x = T)
names(temp)[2] = "CAN_LAST_SRTR_LAB_MELD_desp"
wp1_LI = merge(wp1_LI, temp, by.x = "CAN_LAST_SRTR_LAB_MELD", by.y = "Candidate's current Medical Urgency", all.x = T)
names(temp)[2] = "CAN_LAST_STAT_desp"
wp1_LI = merge(wp1_LI, temp, by.x = "CAN_LAST_STAT", by.y = "Candidate's current Medical Urgency", all.x = T)
# CAN_INIT_ACT_STAT_CD
# names(temp)[2] = "CAN_LAST_STAT_desp"
# wp1_LI = merge(wp1_LI, temp, by.x = "CAN_LAST_STAT", by.y = "Candidate's current Medical Urgency", all.x = T)

```

```{r}
write.csv(wp1_LI, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/waitlist.csv", row.names = F)
```

# Transplant Folow-up Data:
```{r}
txf = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/txf_li.csv")
```

```{r}
names(wl)
```
```{r}
uniqueN(txf$PX_ID)

uniqueN(wl$PX_ID)
# Retain records of only those PX_IDs that are there in the "wl" file
txf = txf[txf$PX_ID %in% wl$PX_ID, ]

write.csv(txf, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/txf_recent.csv", row.names = F)

temp = data.table(txf)[, list(cnt = .N), by = "PX_ID"]
uniqueN(txf$TRR_FOL_ID)
uniqueN(txf$TRR_ID)
```

# Status-history file:
```{r}
df_hist = read.csv("/Volumes/GoogleDrive/My Drive/SRTR/From SRTR/pubsaf1903/stathist_liin.csv")
names(df_hist)
```
```{r}
df_hist$CANHX_BEGIN_DT = as.Date(df_hist$CANHX_BEGIN_DT, format= "%Y-%m-%d")
df_hist$CANHX_END_DT = as.Date(df_hist$CANHX_END_DT, format= "%Y-%m-%d")
df_hist$CAN_INIT_ACT_STAT_DT = as.Date(df_hist$CAN_INIT_ACT_STAT_DT, format= "%Y-%m-%d")
df_hist$CAN_INIT_INACT_STAT_DT = as.Date(df_hist$CAN_INIT_INACT_STAT_DT, format= "%Y-%m-%d")
df_hist$CAN_LAST_ACT_STAT_DT = as.Date(df_hist$CAN_LAST_ACT_STAT_DT, format= "%Y-%m-%d")
df_hist$CAN_LAST_INACT_STAT_DT = as.Date(df_hist$CAN_LAST_INACT_STAT_DT, format= "%Y-%m-%d")
df_hist$CAN_LISTING_DT = as.Date(df_hist$CAN_LISTING_DT, format= "%Y-%m-%d")
df_hist$CAN_REM_DT = as.Date(df_hist$CAN_REM_DT, format= "%Y-%m-%d")

temp = df_hist[1:10, ]

df_hist1 = subset(df_hist, CAN_LISTING_DT > "2002-12-31")

samp = subset(df_hist1, PX_ID == "362668")

df_hist1$time_period = df_hist1$CANHX_END_DT - df_hist1$CANHX_BEGIN_DT
```

```{r}
# Adding 'STAT_CD_desp'
temp = read_excel("/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_sample.xlsx", sheet = "PTR_STAT_CD")
temp = as.data.frame(temp)
temp[, 1] = as.character(temp[, 1])

colnames(temp)[2] = "CANHX_STAT_CD_desp"
df_hist1 = merge(df_hist1, temp, by.x = "CANHX_STAT_CD", by.y = "Candidate's current Medical Urgency", all.x = T)

colnames(temp)[2] = "CANHX_OPTN_LAB_MELD_desp"
df_hist1 = merge(df_hist1, temp, by.x = "CANHX_OPTN_LAB_MELD", by.y = "Candidate's current Medical Urgency", all.x = T)

colnames(temp)[2] = "CANHX_PREV_LOWER_MELD_SCORE_desp"
df_hist1 = merge(df_hist1, temp, by.x = "CANHX_PREV_LOWER_MELD_SCORE", by.y = "Candidate's current Medical Urgency", all.x = T)

colnames(temp)[2] = "CANHX_SRTR_LAB_MELD_desp"
df_hist1 = merge(df_hist1, temp, by.x = "CANHX_SRTR_LAB_MELD", by.y = "Candidate's current Medical Urgency", all.x = T)

# Adding 'REMCD_desp'
temp = read_excel("/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_sample.xlsx", sheet = "REMCD")
temp = as.data.frame(temp)
temp[, 1] = as.character(temp[, 1])

df_hist1 = merge(df_hist1, temp, by.x = "CAN_REM_CD", by.y = "REMCD", all.x = T)
```


```{r}
df_hist2 = df_hist1[, c("PX_ID", "WL_ORG", "CAN_LISTING_DT", "CANHX_BEGIN_DT", "time_period", "CANHX_END_DT", "CANHX_STAT_CD", "CANHX_STAT_CD_desp", "CAN_INIT_ACT_STAT_DT", "CAN_INIT_INACT_STAT_DT", "CAN_LAST_ACT_STAT_DT", "CAN_LAST_INACT_STAT_DT", "CANHX_EXC_DIAG_HCC1", "CANHX_EXC_DIAG_HCC2", "CANHX_EXC_DIAG_HCC_NOPOLICY", "CANHX_EXC_DIAG_OTHER", "CANHX_EXC_FLG", "CANHX_EXC_SCORE", "CAN_GENDER", "CANHX_HGT_CM", "CANHX_WGT_KG", "CANHX_MELD_DIFF_REASON_CD", "CANHX_OPTN_LAB_MELD", "CANHX_OPTN_LAB_MELD_desp", "CANHX_PREV_LOWER_MELD_SCORE", "CANHX_PREV_LOWER_MELD_SCORE_desp", "CANHX_REASON_STAT_INACT", "CANHX_SRTR_LAB_MELD", "CANHX_SRTR_LAB_MELD_desp", "CAN_REM_DT", "CAN_REM_CD", "CAN_REM_CD_desp", "CAN_SOURCE")]

df_hist2$WL_ORG = as.character(df_hist2$WL_ORG)
df_hist2$WL_ORG = gsub("b'", "", df_hist2$WL_ORG)
df_hist2$WL_ORG = gsub("'", "", df_hist2$WL_ORG)

df_hist2$CAN_SOURCE = as.character(df_hist2$CAN_SOURCE)
df_hist2$CAN_SOURCE = gsub("b'", "", df_hist2$CAN_SOURCE)
df_hist2$CAN_SOURCE = gsub("'", "", df_hist2$CAN_SOURCE)

df_hist2$CAN_GENDER = as.character(df_hist2$CAN_GENDER)
df_hist2$CAN_GENDER = gsub("b'", "", df_hist2$CAN_GENDER)
df_hist2$CAN_GENDER = gsub("'", "", df_hist2$CAN_GENDER)

df_hist2 = subset(df_hist2, WL_ORG == "LI")
```

```{r}
# Adding : CANHX_MELD_DIFF_REASON_CD_descp:
temp = read_excel("/Volumes/GoogleDrive/My Drive/SRTR/Analysis/ptr_li_sample.xlsx", sheet = "MELDDIFF")
temp = as.data.frame(temp)
temp[, 1] = as.character(temp[, 1])

df_hist2 = merge(df_hist2, temp, by = "CANHX_MELD_DIFF_REASON_CD", all.x = T)
df_hist2 = df_hist2[, c(2:29, 1, 34, 30:33)]
```

Write the file:
```{r}
write.csv(df_hist2, "/Volumes/GoogleDrive/My Drive/SRTR/Analysis/stathist_liin_v2.csv", row.names = F)
```

Additonal modifications to the file:
```{r}

```


















