
```{r}
library(readxl)
library(openxlsx)
library(maptools)
library(foreign)
library(dplyr)
library(plyr)
library(fastDummies)
library(Matrix)
library(pracma)
library(SQUAREM)
library(nleqslv)
library(wordspace)

library(data.table)
library(ggplot2)
library(haven)
library(tibble)

print("---")
```

```{r}
computer = "windows" # mac, imac, windows

if (computer == "imac") {
  fol = "/Users/sakshat/Google Drive/SRTR"
} else if (computer == "mac") {
  fol = "/Users/shubham/Google Drive/SRTR"
} else if (computer == "windows") {
  fol = "C:/Users/sakshat/Google Drive/SRTR"
}
ref1 = read.csv(paste0(fol, "/From SRTR/Donor_files/deceasedtodonhosp.csv"), stringsAsFactors = F)
ref2 = read.csv(paste0(fol, "/From SRTR/Donor_files/donorhospital.csv"), stringsAsFactors = F)

names(ref1)[1:4] = paste0("ref1_", names(ref1)[1:4])
names(ref2)[1:2] = paste0("ref2_", names(ref2)[1:2])
```

# Sanity check of 'ref1/2':
```{r}
uniqueN(ref1$DONOR_ID)     # No issue here.
uniqueN(ref2$PROVIDER_NUM)
temp = data.table(ref2)[, list(cnt = .N), by = list(ref2_OPO_CTR_CD, ref2_OPO_CTR_TY, PROVIDER_NUM, PROVIDER_MBR_TY)]

# Since cnt = 1 always, therefore, the unique identifier is: (ref2_OPO_CTR_CD, ref2_OPO_CTR_TY, PROVIDER_NUM, PROVIDER_MBR_TY)

# One other option is to retain only those donor hospitals found in 'df_dist (LSAM file)'.
```

```{r}
df_don = read.csv(paste0(fol, "/Analysis/donor.csv"), stringsAsFactors = F)    # Only deceased donor

df_don$DON_RECOV_DT =  as.Date(df_don$DON_RECOV_DT, format= "%Y-%m-%d"); #sum(is.na(df_don$DON_RECOV_DT))

start_date = as.Date("2010-01-01", format = "%Y-%m-%d")
df_don = df_don[(df_don$DON_RECOV_DT >= start_date), ]
```

# Cross-cheking with OPTN data table:
```{r}
uniqueN(df_don$DONOR_ID)   # All records belong to a new DONOR
df_don$yr = substr(df_don$yr_mon, 1, 4)
unique(df_don$DON_ORG); sum(is.na(df_don$DON_ORG))

table(df_don$yr)

# A patient is associated:
table(df_don[!is.na(df_don$PX_ID), ]$yr)

# Discard code is not there:
table(df_don[is.na(df_don$DON_DISCARD_CD), ]$yr)

sum(is.na(df_don$DON_DISCARD_CD)); sum(!is.na(df_don$PX_ID))

table(df_don$DON_TY)
```


# Merge to attach don_hosp:
```{r}
# Add ref1's information:
df_don = merge(df_don, ref1, by = "DONOR_ID", all.x = T)
sum(is.na(df_don$DON_HOSP_PROV_NUM))

# Add ref2's information (DONOR hospital's information):
df_don = merge(df_don, ref2, by.x = c("ref1_DON_OPO_CTR_CD", "ref1_DON_OPO_CTR_TY", "ref1_DON_HOSP_PROV_NUM", "ref1_DON_HOSP_PROV_TY"),
             by.y = c("ref2_OPO_CTR_CD", "ref2_OPO_CTR_TY", "PROVIDER_NUM", "PROVIDER_MBR_TY"), all.x = T)
sum(is.na(df_don$HOSPITAL_ZIP))
```

# Create don_hosp_id:
```{r}
df_don$don_hosp_id = paste0(df_don$ref1_DON_OPO_CTR_CD, df_don$ref1_DON_HOSP_PROV_NUM, df_don$ref1_DON_HOSP_PROV_TY)
sum(is.na(df_don$don_hosp_id))
```

# Write the file:
```{r}
# write.csv(df_don, paste0(fol, "/Analysis/donor_with_hosp.csv"), row.names = F)

min(df_don$DON_RECOV_DT); max(df_don$DON_RECOV_DT)
```

# Donor hospital wise SUPPLY (9 yrs: 2010 to 2018):
```{r}
temp = data.table(df_don)[, list(supply = .N), by = list(yr_mon, don_hosp_id, DON_OPO_CTR_CD, DON_OPO_REGION)]

df_don$yr = sapply(c(1:nrow(df_don)), function(i) {strsplit(df_don$yr_mon[i], "-")[[1]][1]})
temp = data.table(df_don[df_don$yr != "2019", ])[, list(supply = .N), by = list(yr, don_hosp_id, DON_OPO_CTR_CD, DON_OPO_REGION)]

temp = data.table(df_don[df_don$yr != "2019", ])[, list(supply = .N), by = list(policy, don_hosp_id, DON_OPO_CTR_CD, DON_OPO_REGION)]

temp = data.table(df_don[df_don$yr != "2019", ])[, list(supply = .N), by = list(don_hosp_id, DON_OPO_CTR_CD, DON_OPO_REGION)]

temp = data.table(temp)[, list(supply = .N), by = list(DON_OPO_REGION)]

write.csv(temp, paste0(fol_, "/SRTR/R_files/Equilibrium/Input_data/For_Gurobi/don_hosp_sup.csv"), row.names = F)

sum(temp$supply == 0)
hist(temp$supply)

```

# TC wise DEMAND (9 yrs: 2010 to 2018):
```{r}
### Based on 'Sum_paper.Rmd'  ###
wl = read.csv(paste0(fol, "/From SRTR/pubsaf1903/cand_liin.csv"), stringsAsFactors = F)  # /Volumes/GoogleDrive/My Drive, /Users/shubham/Google Drive

wl$list_date = as.Date(wl$CAN_LISTING_DT, format= "%Y-%m-%d")
min(wl$list_date, na.rm = T); max(wl$list_date, na.rm = T)
wl1= wl[!is.na(wl$list_date) & (wl$list_date >= "2010-01-01") & (wl$list_date < "2019-01-01"), ]
min(wl1$list_date, na.rm = T); max(wl1$list_date, na.rm = T)

wl1$policy = sapply(c(1:nrow(wl1)), function(i) {if (wl1$list_date[i] > "2013-06-17") {return ("post")} else {return ("pre")}}) 

# Linking with INSTITUTION data:
inst = read.csv("/Users/shubham/Google Drive/SRTR/From SRTR/pubsaf1903/institution.csv", stringsAsFactors = F)
temp = inst[, c("CTR_ID", "CTR_CD", "REGION")]

# Add OPO and Region:
colnames(temp) = c("CTR_ID", "CAN_OPO_CD", "CAN_OPO_REGION")
wl1 = merge(wl1, temp, by.x = "CAN_LISTING_OPO_ID", by.y = "CTR_ID", all.x = T)
unique(wl1$CAN_OPO_CD)

# Add TC:
temp = inst[, c("CTR_ID", "CTR_CD")]
colnames(temp) = c("CTR_ID", "CAN_CTR_CD")
wl1 = merge(wl1, temp, by.x = "CAN_LISTING_CTR_ID", by.y = "CTR_ID", all.x = T)
unique(wl1$CAN_CTR_CD)

wl1$yr_mon = substr(as.character(wl1$list_date), 1, 7)
wl1$yr = substr(wl1$list_date, 1, 4)

temp = data.table(wl1)[, list(dem = .N), by = list(yr_mon, CAN_CTR_CD, CAN_OPO_CD, CAN_OPO_REGION)]

temp = data.table(wl1)[, list(dem = .N), by = list(yr, CAN_CTR_CD, CAN_OPO_CD, CAN_OPO_REGION)]

temp = data.table(wl1)[, list(dem = .N), by = list(policy, CAN_CTR_CD, CAN_OPO_CD, CAN_OPO_REGION)]

temp = data.table(wl1)[, list(dem = .N), by = list(CAN_CTR_CD, CAN_OPO_CD, CAN_OPO_REGION)]

write.csv(temp, paste0(fol_, "/SRTR/R_files/Equilibrium/Input_data/For_Gurobi/tc_dem.csv"), row.names = F)

```

# Donor hospital-TC Distance matrix:
```{r}
# Refer to "Distance_matrix.R" file.
```


